version: '2'
name: simple-user-login
services:
  app:
    build: .
    restart: always
    ports:
      - 8080:8080

  mongo:
    image: mongo:latest
    ports:
    - 27017:27017
volumes:
  mongodb_data:
